# Language Support
# Simple language switching functionality

# Supported languages
SUPPORTED_LANGUAGES = {
    'en': 'English',
    'zh': '中文'
}

# Default language
DEFAULT_LANGUAGE = 'en'

# Language translations (simple key-value pairs for common UI elements)
TRANSLATIONS = {
    'en': {
        'home': 'Home',
        'brands': 'Brands',
        'destinations': 'Destinations',
        'my_account': 'My Account & Status',
        'my_stays': 'My Stays',
        'logout': 'Logout',
        'login_join': 'Login / Join',
        'tour_guide': 'Tour Guide',
        'keyboard_shortcuts': 'Keyboard Shortcuts',
        'about_us': 'About Us',
        'sustainability': 'Sustainability',
        'careers': 'Careers',
        'contact_us': 'Contact Us',
        'language': 'Language',
        'quick_links': 'Quick Links',
        'contact': 'Contact',
        'all_rights_reserved': 'All rights reserved',
        'language_changed': 'Language changed to',
        'invalid_language_code': 'Invalid language code',
        # Home page
        'experience_extraordinary': 'Experience the Extraordinary',
        'unforgettable_stays': 'Unforgettable stays in the world\'s most desirable locations.',
        'destination': 'Destination',
        'where_to': 'Where to?',
        'check_in': 'Check-in',
        'check_out': 'Check-out',
        'search': 'SEARCH',
        'advanced_options': 'Advanced Options',
        'guests': 'Guests',
        'our_collection': 'Our Collection',
        'discover_perfect_brand': 'Discover the perfect brand for your journey.',
        'membership': 'Membership',
        'unlock_exclusive_benefits': 'Unlock Exclusive Benefits',
        'join_loyalty_program': 'Join our loyalty program to earn points on every stay, enjoy complimentary upgrades, and access member-only rates.',
        'earn_points': 'Earn Points',
        'free_wifi': 'Free Wi-Fi',
        'late_checkout': 'Late Checkout',
        'join_now': 'Join Now',
        'my_status': 'My Status',
        # Search page
        'night': 'night',
        'nights': 'nights',
        'guest': 'guest',
        'guests_word': 'guest',
        'room': 'room',
        'rooms': 'rooms',
        'properties_found': 'propert',
        'properties_found_plural': 'ies',
        'properties_found_singular': 'y',
        'filter_results': 'Filter Results',
        'dates': 'Dates',
        'sort_by': 'Sort By',
        'best_match': 'Best Match',
        'lowest_price': 'Lowest Price',
        'highest_price': 'Highest Price',
        'highest_rating': 'Highest Rating',
        'lowest_rating': 'Lowest Rating',
        'highest_stars': 'Highest Stars',
        'lowest_stars': 'Lowest Stars',
        'details': 'Details',
        'people': 'People',
        'rooms_label': 'Rooms',
        'amenities': 'Amenities',
        'apply_filters': 'APPLY FILTERS',
        'reset_filters': 'Reset Filters',
        'list_view': 'List View',
        'map_view': 'Map View',
        'room_types': 'Room Types',
        'review': 'review',
        'reviews': 'reviews',
        'matched': 'Matched',
        'more_to': 'more to',
        'amenities_matched': 'Amenities matched:',
        'from': 'From',
        'view': 'View',
        'no_properties_found': 'No properties found',
        'couldnt_find_hotels': 'We couldn\'t find any hotels matching your search criteria for',
        'look_forward_welcoming': 'We look forward to welcoming you here in the future!',
        'browse_all_destinations': 'Browse All Destinations',
        'back_to_home': 'Back to Home',
        'try_adjusting_search': 'Try adjusting your search:',
        'check_different_dates': 'Check different dates',
        'modify_filters': 'Modify your filters',
        'search_different_city': 'Search for a different city',
        # About page
        'our_story': 'Our Story',
        'redefining_hospitality': 'Redefining Hospitality for the Modern Era',
        'lumina_founded': 'Lumina Hospitality was founded on a simple belief: that every journey deserves a memorable stay.',
        'lumina_growth': 'From our humble beginnings as a single boutique hotel, we have grown into a global collection of distinct brands, each designed to cater to a unique travel lifestyle. Whether you seek the pinnacle of luxury, the pulse of the city, family fun, or smart efficiency, Lumina has a home for you.',
        'destinations_stat': 'Destinations',
        'distinct_brands': 'Distinct Brands',
        'passion_for_service': 'Passion for Service',
        'passion_service_desc': 'We go above and beyond to ensure our guests feel valued and cared for.',
        'global_perspective': 'Global Perspective',
        'global_perspective_desc': 'Embracing local cultures while maintaining world-class standards.',
        'sustainability_desc': 'Committed to reducing our environmental footprint in every community we serve.',
        # Contact page
        'contact_us': 'Contact Us',
        'here_to_help': 'We\'re here to help. Get in touch with us.',
        'get_in_touch': 'Get in Touch',
        'have_question': 'Have a question or need assistance? Our team is ready to help you with any inquiries about reservations, services, or general information.',
        'email': 'Email',
        'general_inquiries': 'General Inquiries:',
        'reservations_label': 'Reservations:',
        'customer_service': 'Customer Service:',
        'phone': 'Phone',
        'corporate_office': 'Corporate Office',
        'send_us_message': 'Send Us a Message',
        'name': 'Name',
        'email_label': 'Email',
        'subject': 'Subject',
        'select_subject': 'Select a subject',
        'reservation_inquiry': 'Reservation Inquiry',
        'service': 'Customer Service',
        'feedback': 'Feedback',
        'other': 'Other',
        'message': 'Message',
        'send_message': 'Send Message',
        # Account page
        'hello': 'Hello',
        'member': 'Member',
        'member_number': 'Member #',
        'your_points': 'YOUR POINTS',
        'redeem_points': 'Redeem Points',
        'overview': 'Overview',
        'rewards_wallet': 'Rewards Wallet',
        'account_activity': 'Account Activity',
        'settings': 'Settings',
        'member_benefits': 'Member Benefits',
        'current_status': 'Current Status',
        'until': 'until',
        'here_status_tracker': 'Here\'s your status tracker',
        'by_nights': 'By nights',
        'by_points': 'By points',
        'nights_stayed': 'nights stayed',
        'more_to_tier': 'more to',
        'maximum_tier_achieved': 'Maximum tier achieved!',
        'club_member': 'Club Member',
        'silver_elite': 'Silver Elite',
        'gold_elite': 'Gold Elite',
        'diamond_elite': 'Diamond Elite',
        'platinum_elite': 'Platinum Elite',
        # Account page additional
        'lifetime_points': 'lifetime points',
        'earn_qualifying_nights': 'Earn qualifying nights or points to unlock more member benefits.',
        'search_results': 'Search Results',
        'confirm_booking': 'Confirm Booking',
        'confirm_your_booking': 'Confirm Your Booking',
        'booking_details': 'Booking Details',
        'hotel_label': 'Hotel:',
        'room_type_label': 'Room Type:',
        'nights_label': 'Nights:',
        'rooms_label_detail': 'Rooms:',
        'price_breakdown': 'Price Breakdown',
        'base_rate': 'Base Rate',
        'taxes': 'Taxes',
        'taxes_percent': 'Taxes (10%)',
        'service_fee': 'Service Fee (5%)',
        'breakfast': 'Breakfast',
        'subtotal': 'Subtotal',
        'total': 'Total',
        'points_used': 'points used',
        'points_earned': 'points earned',
        'select_payment': 'Select Payment Method',
        'pay_with_points': 'Pay with Points',
        'pay_with_card': 'Pay with Card',
        'available_points': 'Available Points',
        'points_needed': 'Points Needed',
        'confirm_and_pay': 'Confirm and Pay',
        'my_stays_title': 'My Stays',
        'manage_reservations': 'Manage your hotel reservations and view your stay history',
        'upcoming': 'Upcoming',
        'current': 'Current',
        'past': 'Past',
        'cancelled': 'Cancelled',
        'favorites': 'Favorites',
        'events': 'Events',
        'booking': 'booking',
        'bookings': 'bookings',
        'stay': 'stay',
        'stays': 'stays',
        'total_label': 'Total',
        'breakfast_included': 'Breakfast included',
        'view_details': 'View Details',
        'cancel_booking': 'Cancel Booking',
        'stay_again': 'Stay Again',
        'write_review': 'Write Review',
        'brands_collection': 'A Collection of Distinction',
        'four_brands_one_promise': 'Four Brands. One Promise.',
        'explore_destinations': 'Explore Our Destinations',
        'from_iconic_cities': 'From iconic cities to breathtaking resorts.',
        'see_all_in': 'See all in',
        'no_reviews_yet': 'No reviews yet',
        'book_now': 'Book Now',
        'read_more': 'Read More',
        'show_less': 'Show Less',
        # Sustainability page
        'sustainability_commitment': 'Our commitment to a sustainable future',
        'environmental_commitment': 'Our Environmental Commitment',
        'sustainability_intro': 'At Lumina Hospitality, we believe that luxury and sustainability go hand in hand. We are committed to reducing our environmental footprint while providing exceptional experiences for our guests.',
        'waste_reduction': 'Waste Reduction',
        'waste_reduction_desc': 'We\'ve implemented comprehensive recycling programs and reduced single-use plastics across all our properties by 80%.',
        'energy_efficiency': 'Energy Efficiency',
        'energy_efficiency_desc': 'All our hotels use renewable energy sources and energy-efficient systems, reducing our carbon footprint by 60%.',
        'water_conservation': 'Water Conservation',
        'water_conservation_desc': 'Advanced water management systems help us conserve millions of gallons annually while maintaining guest comfort.',
        'local_community_support': 'Local Community Support',
        'local_community_desc': 'We partner with local communities to support sustainable practices, source locally, and create meaningful employment opportunities.',
        'green_building_standards': 'Green Building Standards',
        'green_building_desc': 'All new properties are built to LEED certification standards, and we\'re retrofitting existing properties to meet these high environmental benchmarks.',
        'goals_2030': 'Our Goals for 2030',
        'renewable_energy': 'Renewable Energy',
        'waste_to_landfill': 'Waste to Landfill',
        'water_reduction': 'Water Reduction',
        # Careers page
        'careers_join_team': 'Join our team and shape the future of hospitality',
        'why_work_with_us': 'Why Work With Us?',
        'careers_intro': 'At Lumina Hospitality, we\'re not just building hotels—we\'re creating experiences. Join a team that values innovation, diversity, and excellence.',
        'inclusive_culture': 'Inclusive Culture',
        'inclusive_culture_desc': 'We celebrate diversity and create an environment where everyone can thrive and grow.',
        'career_growth': 'Career Growth',
        'career_growth_desc': 'Comprehensive training programs and clear career paths help you reach your professional goals.',
        'work_life_balance': 'Work-Life Balance',
        'work_life_balance_desc': 'We believe in supporting our team members with flexible schedules and comprehensive benefits.',
        'open_positions': 'Open Positions',
        'open_positions_desc': 'We\'re always looking for talented individuals to join our team across all departments.',
        'hotel_operations': 'Hotel Operations',
        'front_desk_associates': 'Front Desk Associates',
        'housekeeping_supervisors': 'Housekeeping Supervisors',
        'guest_services_managers': 'Guest Services Managers',
        'corporate': 'Corporate',
        'marketing_specialists': 'Marketing Specialists',
        'revenue_analysts': 'Revenue Analysts',
        'it_support_engineers': 'IT Support Engineers',
        'benefits_perks': 'Benefits & Perks',
        'competitive_salary': 'Competitive salary and performance bonuses',
        'health_insurance': 'Health, dental, and vision insurance',
        'employee_discounts': 'Employee discounts on stays',
        'professional_development': 'Professional development opportunities',
        'paid_time_off': 'Paid time off and holidays',
        'retirement_savings': 'Retirement savings plan',
        'ready_to_join': 'Ready to Join Us?',
        'send_resume': 'Send your resume and cover letter to careers@luminahotels.com',
        'contact_hr_team': 'Contact Our HR Team',
        # Brand detail page
        'our_philosophy': 'Our Philosophy',
        'grand_apex_philosophy': 'Excellence in Every Detail',
        'grand_apex_desc': 'At Grand Apex, we believe luxury is not just a service, but a feeling. Our dedicated concierge teams and opulent environments ensure your stay is nothing short of majestic.',
        'urban_pulse_philosophy': 'The Heartbeat of the City',
        'urban_pulse_desc': 'We bring the energy of the metropolis to your doorstep. Designed for the modern traveler who craves connection, culture, and style in the center of it all.',
        'family_haven_philosophy': 'Memories Made Together',
        'family_haven_desc': 'Vacations are precious. We handle the details so you can focus on what matters most: your loved ones. From kids\' clubs to relaxing spas, there\'s joy for everyone.',
        'metro_express_philosophy': 'Smart Travel, Simplified',
        'metro_express_desc': 'Metro Express respects your journey and your budget. We provide clean, comfortable, and efficient accommodations so you can rest easy and travel further.',
        'our_brand_locations': 'Our Locations',
        'no_hotels_found': 'No hotels found for this brand yet.',
        'view_details': 'VIEW DETAILS',
        # Brand badges
        'luxury': 'Luxury',
        'concierge': 'Concierge',
        'city_center': 'City Center',
        'modern_design': 'Modern Design',
        'kid_friendly': 'Kid Friendly',
        'resort_pools': 'Resort Pools',
        'value': 'Value',
        'convenient': 'Convenient',
        'lifestyle': 'Lifestyle',
        'modern': 'Modern',
        'resort': 'Resort',
        'family': 'Family',
        'budget': 'Budget',
        'smart': 'Smart',
        'explore_brand': 'Explore',
        # Account page additional translations
        'milestone_rewards': 'Milestone Rewards',
        'earn_milestone_rewards': 'Earn Milestone Rewards!',
        'milestone_description': 'Choose your first reward at 20 nights, and again every 10 nights you stay this year, up to 100 nights.',
        'nights_to_next_milestone': 'nights to next milestone',
        'you_have_unclaimed_rewards': 'You have unclaimed rewards!',
        'claim_reward': 'Claim',
        'night_reward': '-Night Reward',
        'milestone_rewards_progress': 'Milestone Rewards progress >',
        'free_nights_booking_rewards': 'Free Nights and Booking Rewards',
        'bonus_points': 'Bonus Points',
        'complimentary_breakfast': 'Complimentary Breakfast',
        'complimentary_breakfasts': 'Complimentary Breakfasts',
        'milestone_reward': '-Night Milestone Reward',
        'claimed': 'Claimed',
        'used': 'used',
        'available': 'available',
        'all_used': 'All used',
        'free_breakfast': 'Free Breakfast',
        'no_free_nights': 'No free nights or booking rewards yet.',
        'start_using_rewards': 'Start Using Rewards',
        'current_tier': 'Current Tier',
        'multiplier': 'Multiplier',
        'total_nights': 'Total Nights',
        'stay': 'stay',
        'stays': 'stays',
        'total_spent': 'Total Spent',
        'points_history': 'Points History',
        'points_calculation': 'Points Calculation: 1 dollar = 10 base points ×',
        'multiplier_text': 'x multiplier. Points are not earned on amounts paid with points.',
        'points_earned_on_payment': 'Points earned on actual payment (excludes points payment)',
        'no_points_transactions': 'No points transactions yet.',
        'show_more': 'Show More',
        'more': 'more',
        'show_less': 'Show Less',
        'profile_information': 'Profile Information',
        'edit_profile': 'Edit Profile',
        'username': 'Username',
        'phone': 'Phone',
        'not_provided': 'Not provided',
        'birthday': 'Birthday',
        'address': 'Address',
        'city': 'City',
        'country': 'Country',
        'postal_code': 'Postal Code',
        'save_changes': 'Save Changes',
        'cancel': 'Cancel',
        'payment_methods': 'Payment Methods',
        'add_card': 'Add Card',
        'expires': 'Expires',
        'default': 'Default',
        'set_default': 'Set Default',
        'no_payment_methods': 'No payment methods saved.',
        'cardholder_name': 'Cardholder Name',
        'card_number': 'Card Number',
        'expiration_month': 'Expiration Month',
        'expiration_year': 'Expiration Year',
        'cvv': 'CVV',
        'not_stored': '(not stored)',
        'cvv_security_note': 'CVV is not stored for security',
        'save_card': 'Save Card',
        'change_password': 'Change Password',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'confirm_password': 'Confirm Password',
        'password_requirements': 'Password must be 8-16 characters and contain at least one letter and one number.',
        'your_membership_benefits': 'Your Membership Benefits',
        'available_with_status': 'Available with your',
        'status': 'status',
        'compare_all_tiers': 'Compare All Club Membership Tiers',
        'benefit': 'Benefit',
        'points_multiplier': 'Points Multiplier',
        'earn_points_on_stays': 'Earn Points on Stays',
        'club_member_only_rates': 'Club Member-only Rates',
        'mobile_checkin': 'Mobile Check-in',
        'late_checkout': 'Late Checkout',
        'welcome_amenity': 'Welcome Amenity',
        'priority_support': 'Priority Support',
        'priority_checkin': 'Priority Check-in',
        'room_upgrade': 'Room Upgrade',
        'suite_upgrade': 'Suite upgrade',
        'penthouse_upgrade': 'Penthouse upgrade',
        'executive_lounge_access': 'Executive Lounge Access',
        'dedicated_concierge': 'Dedicated Concierge',
        'personal_travel_advisor': 'Personal Travel Advisor',
        'exclusive_events_access': 'Exclusive Events Access',
        'complimentary_spa_services': 'Complimentary Spa Services',
        'airport_transfers': 'Airport Transfers',
        'subject_to_availability': 'Subject to availability',
        'tier_retention_rules': 'Tier Retention Rules',
        'how_tier_retention_works': 'How Tier Retention Works:',
        'to_maintain_status': 'To maintain your',
        'status_valid_until': 'status, you need to meet the retention requirements each year. Your tier status is valid until',
        'your_retention_requirements': 'Your Retention Requirements:',
        'qualifying_nights': 'qualifying nights',
        'or': 'OR',
        'retention_requirement_met': 'Retention Requirement Met',
        'retention_requirement_not_met': 'Retention Requirement Not Met',
        'current_progress': 'Current Progress (this tier year):',
        'days_to_meet_requirement': 'You have',
        'days_to_maintain_status': 'days to meet the requirement to maintain your status.',
        'important_notes': 'Important Notes:',
        'retention_resets': 'Retention requirements reset each year on your tier anniversary date',
        'meet_one_requirement': 'You only need to meet ONE requirement (nights OR points) to retain your status',
        'downgrade_note': 'If you don\'t meet the requirement, you\'ll be downgraded to the tier you qualify for based on your lifetime nights/points',
        'qualifying_counted': 'Qualifying nights and points are counted from stays completed during your tier year',
        'close': 'Close',
        'click_to_view_retention': 'Click to view retention rules',
        'earn_qualifying_nights': 'Earn qualifying nights or points to unlock more member benefits.',
        'email': 'Email',
        'cancelled': 'Cancelled',
        'member': 'Member',
        'club_member_tier': 'Club Member',
        'silver_elite_tier': 'Silver Elite',
        'gold_elite_tier': 'Gold Elite',
        'diamond_elite_tier': 'Diamond Elite',
        'platinum_elite_tier': 'Platinum Elite',
        'n_a': 'N/A',
        # Footer
        'redefining_luxury_comfort': 'Redefining luxury and comfort across the globe. Experience the extraordinary with our collection of distinct brands.',
        # Hotel detail page
        'room_types': 'Room Types',
        'guest': 'guest',
        'guests': 'guests',
        'amenity': 'amenity',
        'amenities': 'amenities',
        'per_night': 'per night',
        'sold_out': 'Sold Out',
        'only_left': 'Only',
        'left': 'left',
        'view_details': 'View Details',
        'guest_reviews': 'Guest Reviews',
        'no_reviews_yet_first': 'No reviews yet. Be the first to review this hotel!',
        'show_more_reviews': 'Show More Reviews',
        'more_reviews': 'more',
        'you_might_also_like': 'You Might Also Like',
        'map_unavailable': 'Map unavailable',
        'review': 'review',
        'reviews': 'reviews',
        # Room type detail page
        'room_description': 'Room Description',
        'experience_comfort_style': 'Experience comfort and style in this beautifully designed room.',
        'included_amenities': 'Included Amenities',
        'no_amenities_listed': 'No amenities listed for this room type.',
        'no_image_available': 'No image available',
        'incl_tax': 'incl. tax',
        'earn_points_per_night': 'Earn',
        'points_per_night': 'points per night',
        'rooms_required': 'Rooms Required',
        'add_breakfast': 'Add Breakfast',
        'per_room_per_stay': 'per room per stay',
        'please_login_to_book': 'Please',
        'login_to_book': 'login',
        'to_book_and_earn': 'to book and earn points.',
        # Milestone rewards page
        'congratulations_milestone': 'Congratulations! You\'ve reached',
        'nights_this_year': 'nights this year. Choose your reward:',
        'bonus_points_title': 'Bonus Points',
        'get_bonus_points': 'Get',
        'bonus_points_added': 'bonus points added to your account immediately. Use them for future bookings or rewards.',
        'claim_points': 'Claim',
        'points_text': 'Points',
        'complimentary_breakfasts_title': 'Complimentary Breakfasts',
        'enjoy_breakfasts': 'Enjoy',
        'complimentary_breakfasts_valued': 'complimentary breakfasts (valued at $25 each) on your next stay. Valid for one year.',
        'claim_breakfasts': 'Claim',
        'breakfasts_text': 'Breakfasts',
        'back_to_my_account': 'Back to My Account',
        # Milestone progress page
        'milestone_rewards_progress_title': 'Milestone Rewards Progress',
        'track_progress_view': 'Track your progress and view all milestone rewards for',
        'how_milestone_rewards_work': 'How Milestone Rewards Work',
        'earn_milestone_every_10': 'Earn Milestone Rewards Every 10 Nights',
        'starting_at_20_nights': 'Starting at 20 nights, you can claim a reward every 10 nights you stay (20, 30, 40, 50, 60, 70, 80, 90, 100 nights).',
        'choose_your_reward': 'Choose Your Reward',
        'at_each_milestone_choose': 'At each milestone, choose between 5,000 bonus points or 2 complimentary breakfasts.',
        'annual_reset': 'Annual Reset',
        'milestone_progress_resets': 'Milestone progress resets each calendar year. Nights count from January 1st to December 31st.',
        'use_your_rewards': 'Use Your Rewards',
        'points_added_immediately': 'Points are added to your account immediately. Breakfast vouchers can be used on your next booking.',
        'your_milestone_progress': 'Your',
        'milestone_progress': 'Milestone Progress',
        'nights_milestone': 'Nights Milestone',
        'claimed': 'Claimed',
        'available': 'Available',
        'not_reached': 'Not Reached',
        'your_progress': 'Your Progress',
        'nights_needed': 'Nights Needed',
        'more_nights': 'more nights',
        'reward_claimed': 'Reward Claimed:',
        'available_rewards': 'Available Rewards:',
        'claim_your_reward': 'Claim Your Reward',
        'no_milestone_progress_yet': 'No Milestone Progress Yet',
        'start_booking_stays': 'Start booking stays to earn milestone rewards!',
        'book_your_first_stay': 'Book Your First Stay',
        # Booking confirm page additional
        'you_will_earn': 'You will earn',
        'after_your_stay': 'after your stay',
        'payment': 'Payment',
        'payment_method': 'Payment Method',
        'pay_by_card': 'Pay by Card',
        'credit_or_debit_card': 'Credit or debit card',
        'no_saved_payment_methods': 'No saved payment methods.',
        'add_card_in_settings': 'Add a card in Settings',
        'please_select_payment_card': 'Please select a payment card or choose another payment method.',
        'pay_at_hotel': 'Pay at Hotel',
        'pay_upon_arrival': 'Pay upon arrival',
        'pay_with_points': 'Pay with Points',
        'points_equals_dollar': '100 points = $1.00',
        'your_points_label': 'Your Points:',
        'points_needed_label': 'Points Needed:',
        'remaining_balance': 'Remaining Balance:',
        'insufficient_points_warning': 'Insufficient points. Please choose another payment method or add more points.',
        'total_amount': 'Total Amount',
        'complete_booking': 'Complete Booking',
        'back_to_room_details': 'Back to Room Details',
        'use_breakfast_voucher': 'Use Breakfast Voucher',
        'pay_for_breakfast': 'Pay for Breakfast',
        'breakfast_available': 'available',
        'of': 'of',
        'free': 'Free',
        'total_text': 'total',
        # My stays page additional
        'no_current_stays': 'No Current Stays',
        'not_checked_in': 'You\'re not currently checked in to any hotels',
        'book_your_stay': 'Book Your Stay',
        'no_upcoming_stays': 'No Upcoming Stays',
        'no_upcoming_reservations': 'You don\'t have any upcoming reservations',
        'book_your_next_stay': 'Book Your Next Stay',
        'no_past_stays': 'No Past Stays',
        'completed_stays_appear': 'Your completed stays will appear here',
        'book_your_first_stay': 'Book Your First Stay',
        'no_cancelled_bookings': 'No Cancelled Bookings',
        'no_cancelled_reservations': 'You haven\'t cancelled any reservations',
        'explore_hotels': 'Explore Hotels',
        'no_favorite_hotels': 'No Favorite Hotels',
        'no_favorites_yet': 'You haven\'t added any hotels to your favorites yet',
        'click_heart_to_add': 'Click the heart icon on any hotel to add it to your favorites',
        'events_coming_soon': 'Events Coming Soon',
        'events_will_appear': 'Special hotel events, promotions, and exclusive offers will appear here',
        'check_in_in': 'Check-in in',
        'day': 'day',
        'days': 'days',
        'confirmed': 'Confirmed',
        'active_stay': 'Active Stay',
        'completed': 'Completed',
        'view_bill': 'View Bill',
        'edit_review': 'Edit Review',
        'earned_points': 'Earned',
        'free_voucher': 'Free (Voucher)',
        'room_types_available': 'Room Type',
        'room_types_available_plural': 'Room Types',
        'available_text': 'Available',
        'view_hotel_details': 'View hotel details for room availability',
        'view': 'View'
    },
    'zh': {
        'home': '首页',
        'brands': '品牌',
        'destinations': '目的地',
        'my_account': '我的账户',
        'my_stays': '我的住宿',
        'logout': '退出',
        'login_join': '登录 / 注册',
        'tour_guide': '使用指南',
        'keyboard_shortcuts': '快捷键',
        'about_us': '关于我们',
        'sustainability': '可持续发展',
        'careers': '职业发展',
        'contact_us': '联系我们',
        'language': '语言',
        'quick_links': '快速链接',
        'contact': '联系方式',
        'all_rights_reserved': '版权所有',
        'language_changed': '语言已切换为',
        'invalid_language_code': '无效的语言代码',
        # Home page
        'experience_extraordinary': '纵享非凡体验',
        'unforgettable_stays': '在世界最理想的地点享受难忘的住宿体验。',
        'destination': '目的地',
        'where_to': '去哪里？',
        'check_in': '入住',
        'check_out': '退房',
        'search': '搜索',
        'advanced_options': '高级选项',
        'guests': '客人',
        'our_collection': '我们的品牌',
        'discover_perfect_brand': '发现最适合您旅程的品牌。',
        'membership': '会员',
        'unlock_exclusive_benefits': '解锁专属优惠',
        'join_loyalty_program': '加入我们的忠诚度计划，每次住宿赚取积分，享受免费升级和会员专属价格。',
        'earn_points': '赚取积分',
        'free_wifi': '免费Wi-Fi',
        'late_checkout': '延迟退房',
        'join_now': '立即加入',
        'my_status': '我的状态',
        # Search page
        'night': '晚',
        'nights': '晚',
        'guest': '位客人',
        'guests_word': '位客人',
        'room': '间房',
        'rooms': '间房',
        'properties_found': '找到',
        'properties_found_plural': '处房产',
        'properties_found_singular': '处房产',
        'filter_results': '筛选结果',
        'dates': '日期',
        'sort_by': '排序方式',
        'best_match': '最佳匹配',
        'lowest_price': '最低价格',
        'highest_price': '最高价格',
        'highest_rating': '最高评分',
        'lowest_rating': '最低评分',
        'highest_stars': '最高星级',
        'lowest_stars': '最低星级',
        'details': '详细信息',
        'people': '人数',
        'rooms_label': '房间',
        'amenities': '设施',
        'apply_filters': '应用筛选',
        'reset_filters': '重置筛选',
        'list_view': '列表视图',
        'map_view': '地图视图',
        'room_types': '房型',
        'review': '条评价',
        'reviews': '条评价',
        'matched': '匹配',
        'more_to': '还需',
        'amenities_matched': '匹配的设施：',
        'from': '起价',
        'view': '查看',
        'no_properties_found': '未找到房产',
        'couldnt_find_hotels': '我们无法找到符合您搜索条件的酒店',
        'look_forward_welcoming': '我们期待未来在这里欢迎您！',
        'browse_all_destinations': '浏览所有目的地',
        'back_to_home': '返回首页',
        'try_adjusting_search': '尝试调整您的搜索：',
        'check_different_dates': '检查不同日期',
        'modify_filters': '修改筛选条件',
        'search_different_city': '搜索不同城市',
        # About page
        'our_story': '我们的故事',
        'redefining_hospitality': '重新定义现代酒店服务',
        'lumina_founded': 'Lumina Hospitality的成立基于一个简单的信念：每一次旅程都值得一次难忘的住宿。',
        'lumina_growth': '从一家精品酒店开始，我们已经发展成为一个拥有独特品牌的全球组合，每个品牌都旨在满足独特的旅行生活方式。无论您追求极致奢华、城市脉搏、家庭乐趣还是智能高效，Lumina都有适合您的选择。',
        'destinations_stat': '目的地',
        'distinct_brands': '独特品牌',
        'passion_for_service': '服务热情',
        'passion_service_desc': '我们竭尽全力确保客人感到被重视和关爱。',
        'global_perspective': '全球视野',
        'global_perspective_desc': '拥抱当地文化，同时保持世界级标准。',
        'sustainability_desc': '致力于在我们服务的每个社区减少环境足迹。',
        # Contact page
        'contact_us': '联系我们',
        'here_to_help': '我们随时为您服务。请与我们联系。',
        'get_in_touch': '联系我们',
        'have_question': '有问题或需要帮助吗？我们的团队随时准备帮助您解答预订、服务或一般信息的任何询问。',
        'email': '电子邮件',
        'general_inquiries': '一般咨询：',
        'reservations_label': '预订：',
        'customer_service': '客户服务：',
        'phone': '电话',
        'corporate_office': '公司办公室',
        'send_us_message': '发送消息',
        'name': '姓名',
        'email_label': '电子邮件',
        'subject': '主题',
        'select_subject': '选择主题',
        'reservation_inquiry': '预订咨询',
        'service': '客户服务',
        'feedback': '反馈',
        'other': '其他',
        'message': '消息',
        'send_message': '发送消息',
        # Account page
        'hello': '您好',
        'member': '会员',
        'member_number': '会员编号',
        'your_points': '您的积分',
        'redeem_points': '兑换积分',
        'overview': '概览',
        'rewards_wallet': '奖励钱包',
        'account_activity': '账户活动',
        'settings': '设置',
        'member_benefits': '会员优惠',
        'current_status': '当前状态',
        'until': '至',
        'here_status_tracker': '这是您的状态追踪器',
        'by_nights': '按住宿晚数',
        'by_points': '按积分',
        'nights_stayed': '住宿晚数',
        'more_to_tier': '还需',
        'maximum_tier_achieved': '已达到最高等级！',
        'club_member': 'Club Member',
        'silver_elite': 'Silver Elite',
        'gold_elite': 'Gold Elite',
        'diamond_elite': 'Diamond Elite',
        'platinum_elite': 'Platinum Elite',
        # Account page additional
        'lifetime_points': '终身积分',
        'earn_qualifying_nights': '赚取符合条件的住宿晚数或积分以解锁更多会员优惠。',
        'search_results': '搜索结果',
        'confirm_booking': '确认预订',
        'confirm_your_booking': '确认您的预订',
        'booking_details': '预订详情',
        'hotel_label': '酒店：',
        'room_type_label': '房型：',
        'nights_label': '晚数：',
        'rooms_label_detail': '房间：',
        'price_breakdown': '价格明细',
        'base_rate': '基础价格',
        'taxes': '税费',
        'taxes_percent': '税费 (10%)',
        'service_fee': '服务费 (5%)',
        'breakfast': '早餐',
        'subtotal': '小计',
        'total': '总计',
        'points_used': '使用积分',
        'points_earned': '获得积分',
        'select_payment': '选择支付方式',
        'pay_with_points': '使用积分支付',
        'pay_with_card': '使用卡片支付',
        'available_points': '可用积分',
        'points_needed': '所需积分',
        'confirm_and_pay': '确认并支付',
        'my_stays_title': '我的住宿',
        'manage_reservations': '管理您的酒店预订并查看住宿历史',
        'upcoming': '即将到来',
        'current': '当前',
        'past': '过去',
        'cancelled': '已取消',
        'favorites': '收藏',
        'events': '活动',
        'booking': '预订',
        'bookings': '预订',
        'stay': '住宿',
        'stays': '住宿',
        'total_label': '总计',
        'breakfast_included': '包含早餐',
        'view_details': '查看详情',
        'cancel_booking': '取消预订',
        'stay_again': '再次入住',
        'write_review': '写评价',
        'brands_collection': '探索我们的品牌',
        'four_brands_one_promise': '四个品牌。一个承诺。',
        'explore_destinations': '探索我们的目的地',
        'from_iconic_cities': '从标志性城市到令人叹为观止的度假胜地。',
        'see_all_in': '查看',
        'no_reviews_yet': '暂无评价',
        'book_now': '立即预订',
        'read_more': '阅读更多',
        'show_less': '收起',
        # Sustainability page
        'sustainability_commitment': '我们对可持续未来的承诺',
        'environmental_commitment': '我们的环保承诺',
        'sustainability_intro': '在Lumina Hospitality，我们相信奢华与可持续发展并行不悖。我们致力于减少环境足迹，同时为客人提供卓越的体验。',
        'waste_reduction': '减少浪费',
        'waste_reduction_desc': '我们实施了全面的回收计划，并在所有酒店将一次性塑料减少了80%。',
        'energy_efficiency': '能源效率',
        'energy_efficiency_desc': '我们所有的酒店都使用可再生能源和节能系统，将碳足迹减少了60%。',
        'water_conservation': '水资源保护',
        'water_conservation_desc': '先进的水资源管理系统帮助我们每年节约数百万加仑的水，同时保持客人的舒适度。',
        'local_community_support': '本地社区支持',
        'local_community_desc': '我们与当地社区合作，支持可持续实践，本地采购，并创造有意义的就业机会。',
        'green_building_standards': '绿色建筑标准',
        'green_building_desc': '所有新物业均按照LEED认证标准建造，我们正在翻新现有物业以满足这些高标准的环境基准。',
        'goals_2030': '我们的2030年目标',
        'renewable_energy': '可再生能源',
        'waste_to_landfill': '垃圾填埋',
        'water_reduction': '水资源减少',
        # Careers page
        'careers_join_team': '加入我们的团队，塑造酒店业的未来',
        'why_work_with_us': '为什么与我们合作？',
        'careers_intro': '在Lumina Hospitality，我们不仅仅是在建造酒店——我们正在创造体验。加入一个重视创新、多样性和卓越的团队。',
        'inclusive_culture': '包容文化',
        'inclusive_culture_desc': '我们庆祝多样性，创造一个让每个人都能茁壮成长和发展的环境。',
        'career_growth': '职业发展',
        'career_growth_desc': '全面的培训计划和清晰的职业道路帮助您实现职业目标。',
        'work_life_balance': '工作与生活平衡',
        'work_life_balance_desc': '我们相信通过灵活的工作安排和全面的福利来支持我们的团队成员。',
        'open_positions': '空缺职位',
        'open_positions_desc': '我们一直在寻找有才华的人加入我们各个部门的团队。',
        'hotel_operations': '酒店运营',
        'front_desk_associates': '前台接待员',
        'housekeeping_supervisors': '客房服务主管',
        'guest_services_managers': '宾客服务经理',
        'corporate': '企业部门',
        'marketing_specialists': '市场营销专员',
        'revenue_analysts': '收益分析师',
        'it_support_engineers': 'IT支持工程师',
        'benefits_perks': '福利与津贴',
        'competitive_salary': '具有竞争力的薪资和绩效奖金',
        'health_insurance': '健康、牙科和视力保险',
        'employee_discounts': '员工住宿折扣',
        'professional_development': '职业发展机会',
        'paid_time_off': '带薪假期和节假日',
        'retirement_savings': '退休储蓄计划',
        'ready_to_join': '准备加入我们吗？',
        'send_resume': '请将您的简历和求职信发送至 careers@luminahotels.com',
        'contact_hr_team': '联系我们的HR团队',
        # Brand detail page
        'our_philosophy': '我们的理念',
        'grand_apex_philosophy': '细节中的卓越',
        'grand_apex_desc': '在Grand Apex，我们相信奢华不仅仅是一种服务，更是一种感受。我们专业的礼宾团队和富丽堂皇的环境确保您的住宿体验尽显尊贵。',
        'urban_pulse_philosophy': '城市的心跳',
        'urban_pulse_desc': '我们将大都市的活力带到您的家门口。专为渴望在中心地带享受连接、文化和风格的现代旅行者而设计。',
        'family_haven_philosophy': '共同创造回忆',
        'family_haven_desc': '假期是珍贵的。我们处理细节，让您可以专注于最重要的事情：您所爱的人。从儿童俱乐部到放松的水疗中心，每个人都能找到快乐。',
        'metro_express_philosophy': '智能旅行，简单便捷',
        'metro_express_desc': 'Metro Express尊重您的旅程和预算。我们提供干净、舒适和高效的住宿，让您可以轻松休息，走得更远。',
        'our_brand_locations': '我们的位置',
        'no_hotels_found': '此品牌暂无酒店。',
        'view_details': '查看详情',
        # Brand badges
        'luxury': '奢华',
        'concierge': '礼宾服务',
        'city_center': '市中心',
        'modern_design': '现代设计',
        'kid_friendly': '儿童友好',
        'resort_pools': '度假村泳池',
        'value': '超值',
        'convenient': '便捷',
        'lifestyle': '生活方式',
        'modern': '现代',
        'resort': '度假村',
        'family': '家庭',
        'budget': '经济',
        'smart': '智能',
        'explore_brand': '探索',
        # Account page additional translations
        'milestone_rewards': '里程碑奖励',
        'earn_milestone_rewards': '赚取里程碑奖励！',
        'milestone_description': '在20晚时选择您的第一个奖励，之后每10晚住宿再次获得奖励，最多100晚。',
        'nights_to_next_milestone': '晚到达下一个里程碑',
        'you_have_unclaimed_rewards': '您有未领取的奖励！',
        'claim_reward': '领取',
        'night_reward': '晚奖励',
        'milestone_rewards_progress': '里程碑奖励进度 >',
        'free_nights_booking_rewards': '免费住宿和预订奖励',
        'bonus_points': '奖励积分',
        'complimentary_breakfast': '免费早餐',
        'complimentary_breakfasts': '免费早餐',
        'milestone_reward': '晚里程碑奖励',
        'claimed': '已领取',
        'used': '已使用',
        'available': '可用',
        'all_used': '已全部使用',
        'free_breakfast': '免费早餐',
        'no_free_nights': '暂无免费住宿或预订奖励。',
        'start_using_rewards': '开始使用奖励',
        'current_tier': '当前等级',
        'multiplier': '倍数',
        'total_nights': '总住宿晚数',
        'stay': '次住宿',
        'stays': '次住宿',
        'total_spent': '总消费',
        'points_history': '积分历史',
        'points_calculation': '积分计算：1美元 = 10基础积分 ×',
        'multiplier_text': '倍。使用积分支付的金额不获得积分。',
        'points_earned_on_payment': '实际支付获得的积分（不包括积分支付）',
        'no_points_transactions': '暂无积分交易记录。',
        'show_more': '显示更多',
        'more': '更多',
        'show_less': '显示更少',
        'profile_information': '个人信息',
        'edit_profile': '编辑资料',
        'username': '用户名',
        'phone': '电话',
        'not_provided': '未提供',
        'birthday': '生日',
        'address': '地址',
        'city': '城市',
        'country': '国家',
        'postal_code': '邮政编码',
        'save_changes': '保存更改',
        'cancel': '取消',
        'payment_methods': '支付方式',
        'add_card': '添加卡片',
        'expires': '到期',
        'default': '默认',
        'set_default': '设为默认',
        'no_payment_methods': '未保存支付方式。',
        'cardholder_name': '持卡人姓名',
        'card_number': '卡号',
        'expiration_month': '到期月份',
        'expiration_year': '到期年份',
        'cvv': 'CVV',
        'not_stored': '（不存储）',
        'cvv_security_note': 'CVV出于安全考虑不会存储',
        'save_card': '保存卡片',
        'change_password': '修改密码',
        'current_password': '当前密码',
        'new_password': '新密码',
        'confirm_password': '确认密码',
        'password_requirements': '密码必须为8-16个字符，包含至少一个字母和一个数字。',
        'your_membership_benefits': '您的会员优惠',
        'available_with_status': '适用于您的',
        'status': '状态',
        'compare_all_tiers': '比较所有会员等级',
        'benefit': '优惠',
        'points_multiplier': '积分倍数',
        'earn_points_on_stays': '住宿赚取积分',
        'club_member_only_rates': '会员专属价格',
        'mobile_checkin': '手机办理入住',
        'late_checkout': '延迟退房',
        'welcome_amenity': '欢迎礼品',
        'priority_support': '优先支持',
        'priority_checkin': '优先入住',
        'room_upgrade': '房间升级',
        'suite_upgrade': '套房升级',
        'penthouse_upgrade': '顶层套房升级',
        'executive_lounge_access': '行政酒廊使用权',
        'dedicated_concierge': '专属礼宾服务',
        'personal_travel_advisor': '个人旅行顾问',
        'exclusive_events_access': '专属活动参与权',
        'complimentary_spa_services': '免费水疗服务',
        'airport_transfers': '机场接送',
        'subject_to_availability': '视供应情况而定',
        'tier_retention_rules': '等级保留规则',
        'how_tier_retention_works': '等级保留如何运作：',
        'to_maintain_status': '要保持您的',
        'status_valid_until': '状态，您需要每年满足保留要求。您的等级状态有效期至',
        'your_retention_requirements': '您的保留要求：',
        'qualifying_nights': '符合条件的住宿晚数',
        'or': '或',
        'retention_requirement_met': '已满足保留要求',
        'retention_requirement_not_met': '未满足保留要求',
        'current_progress': '当前进度（本等级年度）：',
        'days_to_meet_requirement': '您还有',
        'days_to_maintain_status': '天来满足要求以保持您的状态。',
        'important_notes': '重要提示：',
        'retention_resets': '保留要求每年在您的等级周年日重置',
        'meet_one_requirement': '您只需满足一个要求（住宿晚数或积分）即可保留您的状态',
        'downgrade_note': '如果您不满足要求，将根据您的终身住宿晚数/积分降级到符合条件的等级',
        'qualifying_counted': '符合条件的住宿晚数和积分从您等级年度内完成的住宿中计算',
        'close': '关闭',
        'click_to_view_retention': '点击查看保留规则',
        'earn_qualifying_nights': '赚取符合条件的住宿晚数或积分以解锁更多会员优惠。',
        'email': '邮箱',
        'cancelled': '已取消',
        'member': '会员',
        'club_member_tier': '普通会员',
        'silver_elite_tier': '银卡精英',
        'gold_elite_tier': '金卡精英',
        'diamond_elite_tier': '钻石精英',
        'platinum_elite_tier': '白金精英',
        'n_a': '不适用',
        # Footer
        'redefining_luxury_comfort': '重新定义全球奢华与舒适。通过我们独特的品牌系列体验非凡。',
        # Hotel detail page
        'room_types': '房型',
        'guest': '位客人',
        'guests': '位客人',
        'amenity': '项设施',
        'amenities': '项设施',
        'per_night': '每晚',
        'sold_out': '已售罄',
        'only_left': '仅剩',
        'left': '间',
        'view_details': '查看详情',
        'guest_reviews': '客人评价',
        'no_reviews_yet_first': '暂无评价。成为第一个评价此酒店的客人！',
        'show_more_reviews': '显示更多评价',
        'more_reviews': '更多',
        'you_might_also_like': '您可能还喜欢',
        'map_unavailable': '地图不可用',
        'review': '条评价',
        'reviews': '条评价',
        # Room type detail page
        'room_description': '房间描述',
        'experience_comfort_style': '在这间精心设计的房间中体验舒适与风格。',
        'included_amenities': '包含设施',
        'no_amenities_listed': '此房型未列出设施。',
        'no_image_available': '无图片',
        'incl_tax': '含税',
        'earn_points_per_night': '每晚赚取',
        'points_per_night': '积分',
        'rooms_required': '所需房间数',
        'add_breakfast': '添加早餐',
        'per_room_per_stay': '每间房每次住宿',
        'please_login_to_book': '请',
        'login_to_book': '登录',
        'to_book_and_earn': '以预订并赚取积分。',
        # Milestone rewards page
        'congratulations_milestone': '恭喜！您今年已达到',
        'nights_this_year': '晚住宿。选择您的奖励：',
        'bonus_points_title': '奖励积分',
        'get_bonus_points': '获得',
        'bonus_points_added': '奖励积分将立即添加到您的账户。可用于未来预订或奖励。',
        'claim_points': '领取',
        'points_text': '积分',
        'complimentary_breakfasts_title': '免费早餐',
        'enjoy_breakfasts': '享受',
        'complimentary_breakfasts_valued': '份免费早餐（每份价值$25）在您下次住宿时使用。有效期一年。',
        'claim_breakfasts': '领取',
        'breakfasts_text': '份早餐',
        'back_to_my_account': '返回我的账户',
        # Milestone progress page
        'milestone_rewards_progress_title': '里程碑奖励进度',
        'track_progress_view': '跟踪您的进度并查看所有里程碑奖励',
        'how_milestone_rewards_work': '里程碑奖励如何运作',
        'earn_milestone_every_10': '每10晚获得里程碑奖励',
        'starting_at_20_nights': '从20晚开始，您每住宿10晚即可领取一次奖励（20、30、40、50、60、70、80、90、100晚）。',
        'choose_your_reward': '选择您的奖励',
        'at_each_milestone_choose': '在每个里程碑，选择5,000奖励积分或2份免费早餐。',
        'annual_reset': '年度重置',
        'milestone_progress_resets': '里程碑进度每年重置。住宿晚数从1月1日计算到12月31日。',
        'use_your_rewards': '使用您的奖励',
        'points_added_immediately': '积分会立即添加到您的账户。早餐券可在下次预订时使用。',
        'your_milestone_progress': '您的',
        'milestone_progress': '里程碑进度',
        'nights_milestone': '晚里程碑',
        'claimed': '已领取',
        'available': '可用',
        'not_reached': '未达到',
        'your_progress': '您的进度',
        'nights_needed': '所需晚数',
        'more_nights': '更多晚',
        'reward_claimed': '已领取奖励：',
        'available_rewards': '可用奖励：',
        'claim_your_reward': '领取您的奖励',
        'no_milestone_progress_yet': '暂无里程碑进度',
        'start_booking_stays': '开始预订住宿以赚取里程碑奖励！',
        'book_your_first_stay': '预订您的首次住宿',
        # Booking confirm page additional
        'you_will_earn': '您将赚取',
        'after_your_stay': '住宿后',
        'payment': '支付',
        'payment_method': '支付方式',
        'pay_by_card': '使用卡片支付',
        'credit_or_debit_card': '信用卡或借记卡',
        'no_saved_payment_methods': '未保存支付方式。',
        'add_card_in_settings': '在设置中添加卡片',
        'please_select_payment_card': '请选择支付卡片或选择其他支付方式。',
        'pay_at_hotel': '到店支付',
        'pay_upon_arrival': '抵达时支付',
        'pay_with_points': '使用积分支付',
        'points_equals_dollar': '100积分 = $1.00',
        'your_points_label': '您的积分：',
        'points_needed_label': '所需积分：',
        'remaining_balance': '剩余余额：',
        'insufficient_points_warning': '积分不足。请选择其他支付方式或添加更多积分。',
        'total_amount': '总金额',
        'complete_booking': '完成预订',
        'back_to_room_details': '返回房间详情',
        'use_breakfast_voucher': '使用早餐券',
        'pay_for_breakfast': '支付早餐费用',
        'breakfast_available': '可用',
        'of': '的',
        'free': '免费',
        'total_text': '总计',
        # My stays page additional
        'no_current_stays': '当前无住宿',
        'not_checked_in': '您当前未入住任何酒店',
        'book_your_stay': '预订住宿',
        'no_upcoming_stays': '无即将到来的住宿',
        'no_upcoming_reservations': '您没有任何即将到来的预订',
        'book_your_next_stay': '预订下次住宿',
        'no_past_stays': '无过往住宿',
        'completed_stays_appear': '您已完成的住宿将显示在这里',
        'book_your_first_stay': '预订您的首次住宿',
        'no_cancelled_bookings': '无已取消的预订',
        'no_cancelled_reservations': '您尚未取消任何预订',
        'explore_hotels': '探索酒店',
        'no_favorite_hotels': '无收藏酒店',
        'no_favorites_yet': '您尚未添加任何酒店到收藏',
        'click_heart_to_add': '点击任何酒店的心形图标将其添加到收藏',
        'events_coming_soon': '活动即将推出',
        'events_will_appear': '特别酒店活动、促销和专属优惠将显示在这里',
        'check_in_in': '入住倒计时',
        'day': '天',
        'days': '天',
        'confirmed': '已确认',
        'active_stay': '进行中的住宿',
        'completed': '已完成',
        'view_bill': '查看账单',
        'edit_review': '编辑评价',
        'earned_points': '已赚取',
        'free_voucher': '免费（券）',
        'room_types_available': '种房型',
        'room_types_available_plural': '种房型',
        'available_text': '可用',
        'view_hotel_details': '查看酒店详情了解房间可用性',
        'view': '查看'
    }
}

def get_current_language(session):
    """Get current language from session, default to English"""
    return session.get('language', DEFAULT_LANGUAGE)

def set_language(session, lang_code):
    """Set language in session"""
    if lang_code in SUPPORTED_LANGUAGES:
        session['language'] = lang_code
        return True
    return False

def get_translation(session, key, default=None):
    """Get translation for a key in current language"""
    lang = get_current_language(session)
    return TRANSLATIONS.get(lang, {}).get(key, default or key)

